
/* ================================================================ *
 *          Automatically generated by n-Blocks Studio 2.0          *
 *                                                                  *
 *                         www.n-blocks.net                         *
 * ================================================================ */
#include "nlib\nblocks.h"
#include "nlib\BSP\bsp.h"
// Custom nodes:
#include "nlib\Ticker\ticker.h"
#include "nlib\Counter\counter.h"
#include "nlib\StringFormat\stringformat.h"
#include "nlib\StringSerial\stringserial.h"
#include "nlib\FlipFlop\flipflop.h"
#include "nlib\GPOUT\gpout.h"

// -*-*- List of node objects -*-*-
nBlock_Ticker        nb_nBlockNode0_Ticker   (1000);
nBlock_FlipFlop      nb_nBlockNode1_FlipFlop (0);
nBlock_GPOUT         nb_nBlockNode2_GPOUT    (P2_1, PullNone, 1);

// -*-*- List of connection objects -*-*-
nBlockConnection    n_conn0( &nb_nBlockNode1_FlipFlop, 0,    &nb_nBlockNode2_GPOUT,    0);
nBlockConnection    n_conn1( &nb_nBlockNode0_Ticker,   0,    &nb_nBlockNode1_FlipFlop, 0);


// -*-*- Main function -*-*-
int main(void) {
    SetupWorkbench();
    while(1) {
        ProgressNodes();
        
        // Your custom code here!
    }
}
